#!/usr/bin/env sh

##############################################################################
##
##  UN*X start script for ade-xjc example
##
##############################################################################

OUTPUT="src-gen"
PACKAGE="ade.sub.jaxb"
BINDING="binding.xjb"
SCHEMA="CityGML-SubsurfaceADE-0_9_0.xsd"

exec ../ade-xjc -clean -output $OUTPUT -package $PACKAGE -binding $BINDING $SCHEMA